spring.application.name=firstAi
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:1b
spring.datasource.url=jdbc:mysql://localhost:3306/aiNotes
spring.datasource.username=root
spring.datasource.password=Happy@9415841594
